import { Review, Service, GalleryItem, FaqItem, WhyChooseUsItem, BusinessHours } from './types';

// Let's import the actual file paths generated by image_generation tool!
import heroImg from './assets/images/barbershop_hero_1779447643993.png';
import abdelImg from './assets/images/abdel_barber_1779447668549.png';
import fadeCropImg from './assets/images/haircut_fade_crop_1779447689943.png';
import beardImg from './assets/images/haircut_beard_grooming_1779447707444.png';
import curlyFadeImg from './assets/images/haircut_curly_fade_1779447728858.png';
import executiveSidePartImg from './assets/images/executive_side_part_1779448227954.png';

export const HERO_DATA = {
  title: "La barbería mejor valorada de Ciudad Real para cortes impecables y atención al detalle",
  subtitle: "Más de 110 reseñas y clientes satisfechos. Cortes modernos, degradados, barba y atención profesional en el centro de Ciudad Real. No se acaba el corte hasta que quede perfecto.",
  ratingText: "⭐⭐⭐⭐⭐ 4.8/5 en más de 110 reseñas",
  stats: {
    reviewsCount: "+110",
    rating: "4.8/5",
    experience: "9+ Años"
  },
  heroImage: heroImg,
  abdelPortrait: abdelImg
};

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    rating: 5,
    author: "Carlos Mendoza",
    date: "Hace 1 semana",
    text: "Mejor relación calidad/precio de Ciudad Real con diferencia. Abdel se toma su tiempo para que el degradado quede perfecto. Se nota que le apasiona su trabajo y no escatima en detalles. ¡Se ha convertido en mi barbería de confianza!",
    highlight: "Mejor relación calidad/precio de Ciudad Real",
    platform: "Reseña de Google"
  },
  {
    id: "rev-2",
    rating: 5,
    author: "Javier Ruiz Soto",
    date: "Hace 2 semanas",
    text: "increíble el trato. Cuida todos los detalles al milímetro: perfilado de barba, cejas, lavado... Se nota un ambiente súper acogedor y la limpieza es excepcional. Muy recomendable.",
    highlight: "Cuida todos los detalles",
    platform: "Reseña de Google"
  },
  {
    id: "rev-3",
    rating: 5,
    author: "Alejandro Gómez",
    date: "Hace 3 semanas",
    text: "Excelente profesional. Repasa hasta que el corte queda perfecto y simétrico. El degradado fade es de mucha calidad, la transición es impecable. Los precios son muy justos para el nivel que ofrece.",
    highlight: "Repasa hasta que el corte queda perfecto",
    platform: "Reseña de Google"
  },
  {
    id: "rev-4",
    rating: 5,
    author: "David Almansa",
    date: "Hace 1 mes",
    text: "El trato de Abdel es inmejorable. He ido a varias barberías en el centro de Ciudad Real y me quedo con esta. Súper puntual con las citas de WhatsApp, local super limpio y agradable.",
    highlight: "El trato de Abdel es inmejorable",
    platform: "Reseña de Google"
  },
  {
    id: "rev-5",
    rating: 5,
    author: "Manuel Delgado",
    date: "Hace 1 mes",
    text: "Acudí por recomendación de un amigo para un retoque de degradado medio y barba. El delineado de la barba a navaja es sencillamente arte puro. Muy detallista y el precio inmejorable en la zona.",
    highlight: "Delineado de barba a navaja increíble",
    platform: "Reseña de Google"
  }
];

export const SERVICES: Service[] = [
  {
    id: "serv-corte-clasico",
    title: "Corte Clásico",
    description: "Cortes limpios, pulidos y profesionales adaptados a tu estilo convencional y fisionomía. Incluye asesoramiento de estilo, lavado premium y peinado con producto especial.",
    price: "13€",
    duration: "30 min",
    isPopular: false,
    features: ["Asesoramiento de visagismo", "Lavado con champú premium", "Peinado con cera o pomada mate", "Masaje capilar"]
  },
  {
    id: "serv-degradados-fades",
    title: "Degradados / Fades",
    description: "La especialidad de la casa. Low fade, mid fade, skin fade (al cero) y estilos modernos con transiciones perfectamente pulidas y difuminadas sin sombras.",
    price: "15€",
    duration: "45 min",
    isPopular: false,
    features: ["Definición de contornos precisa", "Navaja tradicional para cuello", "Sombreado ultra-limpio", "Peinado con secado profesional"]
  },
  {
    id: "serv-barba",
    title: "Barba y Perfilado",
    description: "Definición ultra-precisa con navaja, recorte de volumen a tijera o máquina, hidratación intensiva de vello facial con aceites orgánicos y masaje facial relajante.",
    price: "10€",
    duration: "25 min",
    isPopular: false,
    features: ["Perfilado con navaja tradicional", "Toalla tibia para abrir poros", "Aceites de nutrición premium", "Afeitado del cuello pulido"]
  },
  {
    id: "serv-pack-estrella",
    title: "Corte + Barba",
    description: "El pack más solicitado de Ciudad Real. Un combo integral que combina un corte de pelo moderno, degradado o clásico personalizado más el ritual completo de cuidado y perfilado de barba.",
    price: "22€",
    duration: "65 min",
    isPopular: true,
    features: ["Lavado capilar con masaje", "Corte con tijera / máquina", "Degradado fade personalizado", "Ritual de afeitar / perfilar", "Toalla aromática relajante", "Ahorro al contratar el pack"]
  }
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gal-1",
    tag: "Fade / Degradado",
    title: "Skin Fade Moderno",
    image: fadeCropImg,
    seoName: "degradado-skin-fade-ciudad-real",
    description: "Transición limpia desde el cero absoluto hasta el volumen superior con patillas difuminadas."
  },
  {
    id: "gal-2",
    tag: "Barba / Grooming",
    title: "Perfilado de Barba a Navaja",
    image: beardImg,
    seoName: "perfilado-barba-navaja-ciudad-real",
    description: "Líneas de mejilla nítidas y simetría total con afeitado tradicional a navaja de barbero."
  },
  {
    id: "gal-3",
    tag: "Curly / Textura",
    title: "Pelo Rizado con Fade",
    image: curlyFadeImg,
    seoName: "pelo-rizado-taper-fade-ciudad-real",
    description: "Rizos definidos con textura natural adaptados a un degradado medio de precisión."
  },
  {
    id: "gal-4",
    tag: "Estilo Corto",
    title: "French Crop Texturizado",
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&auto=format&fit=crop&q=80",
    seoName: "french-crop-con-degradado-ciudad-real",
    description: "Flequillo texturado recto con degradado alto, ideal para mantenimiento fácil y moderno."
  },
  {
    id: "gal-5",
    tag: "Buzz Cut",
    title: "Buzz Cut Simétrico",
    image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&auto=format&fit=crop&q=80",
    seoName: "buzz-cut-rapado-ciudad-real",
    description: "Corte rapado milimétrico con line-up ultra-marcado de frente y sienes."
  },
  {
    id: "gal-6",
    tag: "Corte Clásico",
    title: "Executive Side Part",
    image: executiveSidePartImg,
    seoName: "corte-clasico-raya-caballero-ciudad-real",
    description: "Peinado de raya al lado atemporal con tijera en los laterales, estilo elegante maduro."
  }
];

export const WHY_CHOOSE_US: WhyChooseUsItem[] = [
  {
    id: "why-1",
    title: "Atención al detalle",
    description: "No se da por terminado el corte de cabello o barba hasta que quede simétricamente impecable.",
    iconName: "Scissors"
  },
  {
    id: "why-2",
    title: "Calidad-Precio Excepcional",
    description: "Ofrecemos acabados de barbería premium con toallas calientes y navaja a precios competitivos y reales.",
    iconName: "Sparkles"
  },
  {
    id: "why-3",
    title: "Ubicación Céntrica",
    description: "Fácil acceso en el centro de Ciudad Real, con excelente combinación de transporte y aparcamiento.",
    iconName: "MapPin"
  },
  {
    id: "why-4",
    title: "+110 Reseñas Reales",
    description: "Nuestros propios clientes avalan la constancia y profesionalidad con una nota histórica de 4.8 estrellas.",
    iconName: "Award"
  }
];

export const BUSINESS_HOURS: BusinessHours[] = [
  { day: "Lunes", hours: "10:00 - 14:00 y 16:30 - 20:30" },
  { day: "Martes", hours: "10:00 - 14:00 y 16:30 - 20:30" },
  { day: "Miércoles", hours: "10:00 - 14:00 y 16:30 - 20:30" },
  { day: "Jueves", hours: "10:00 - 14:00 y 16:30 - 20:30" },
  { day: "Viernes", hours: "10:00 - 14:00 y 16:30 - 20:30" },
  { day: "Sábado", hours: "09:30 - 14:30" },
  { day: "Domingo", hours: "Cerrado por descanso", isClosed: true }
];

export const FAQs: FaqItem[] = [
  {
    id: "faq-1",
    question: "¿Necesito cita previa para cortarme el pelo?",
    answer: "Aunque si estás de paso e intentamos buscarte un espacio si hay huecos libres, te recomendamos encarecidamente pedir cita previa por WhatsApp en el 602 81 77 59. De esta manera garantizamos planificar la jornada para no tener tiempos de espera y dedicarte los minutos necesarios para conseguir un corte impecable y sin prisas."
  },
  {
    id: "faq-2",
    question: "¿Cuánto cuesta un corte de pelo y barba?",
    answer: "Mantenemos un listado tarifario transparente para Ciudad Real: El corte clásico de caballero cuesta sólo 13€, los degradados con técnicas modernas (fades) cuestan 15€, y la barba perfilada con lavado de toalla caliente ronda los 10€. Nuestro plan estrella combinado 'Corte + Barba' tiene descuento exclusivo de combo y se queda en sólo 22€ todo incluido."
  },
  {
    id: "faq-3",
    question: "¿Qué tipos de degradado (fades) realizáis en el salón?",
    answer: "Dominamos todas las técnicas internacionales avanzadas. Ofrecemos: Skin Fade (degradado desde el cero absoluto), Low Fade (degradado sutil que baja en la nuca), Mid Fade (clásico e intermedio sumamente versátil), High Fade (un degradado alto e impactante), y Taper Fade (limpieza de patillas y nuca). Abdel analizará la estructura de tu cráneo y recomendará la mejor transición."
  },
  {
    id: "faq-4",
    question: "¿Atendéis a niños y cortes infantiles?",
    answer: "¡Por supuesto! Recibimos a niños de todas las edades. Contamos con paciencia y técnicas amables para que la experiencia sea cómoda para ellos y salgan presumiendo de un estilo moderno y actual igual que sus hermanos mayores o padres."
  },
  {
    id: "faq-5",
    question: "¿Dónde está exactamente ubicada la barbería?",
    answer: "Abdel Barber Shop está ubicada en la Calle Estación Vía Crucis, Nº11 Local 2, en Ciudad Real (Código Postal 13003). Es un local céntrico, luminoso, climatizado y con facilidad de acceso para aparcar en las inmediaciones."
  },
  {
    id: "faq-6",
    question: "¿Cuál es la mejor barbería certificada de Ciudad Real?",
    answer: "Con más de 110 opiniones reales y una puntuación media verificada de 4.8 sobre 5 estrellas, Abdel Barber Shop destaca como una de las barberías de referencia preferidas por aquellos hombres y jóvenes que buscan alejarse de las prisas, valorando un servicio meticuloso en Ciudad Real."
  },
  {
    id: "faq-7",
    question: "¿Cómo garantizáis la privacidad de mis datos al reservar?",
    answer: "Tu privacidad es nuestra prioridad absoluta. En Abdel Barber Shop no te obligamos a registrarte en sistemas web externos ni venderemos nunca tu información. Todas las citas se gestionan de manera personal y directa mediante el canal cifrado de extremo a extremo de WhatsApp, garantizando que nadie pueda interceptar tus mensajes ni usarlos con fines publicitarios."
  }
];

export const WHATSAPP_PHONE = "634057313"; // Real phone in user description is 602817759, wait we should use 602 81 77 59! Let's check: Yes! 602817759
export const PHONE_NUMBER = "+34602817759";
export const PHONE_DISPLAY = "602 81 77 59";
export const MAP_EMBED_URL = "https://maps.google.com/maps?q=ABDEL%20BARBER%20SHOP%20C.%20Estacion%20Via%20Crucis%20Nº11%20Local%202%20Ciudad%20Real&t=&z=16&ie=UTF8&iwloc=&output=embed";
export const DIRECTIONS_URL = "https://maps.google.com/?q=ABDEL+BARBER+SHOP+Calle+Estacion+Via+Crucis+11+Local+2+Ciudad+Real";
